### ISSUE TITLE
support foreign architectures

### ISSUE THREAD

**Issue by npf** [oar-team/kameleon-bootstrap-recipes#3]
For now, it seems that only i386 on x86_64 is supported as cross build.

With not changing to much code we should be able to support other foreign architecture, either using qemu-user in chroot, or qemu-system in emulated VM.

**Comment by mickours** [comment]
Did you managed to make it work with ARM 32?

**Comment by mickours** [comment]
@npf what about this one?

**Comment by npf** [comment]
arm64 build with in kameleon-recipes/from_scratch, closing.
